### ISSUE TITLE
Very Interesting~

### ISSUE THREAD

**Issue by dianqk** [carlosypunto/ReallySimpleMVVMLoginExampleWithRxSwift#3]
But I have a problem, why you use `weak static var`, other than `static var`

``` swift
private extension UIStoryboard {

    weak static var mainStoryboard: UIStoryboard? {
        return UIStoryboard(name: "Main", bundle: NSBundle.mainBundle())
    }

    weak static var loginNC: LoginNavigationController? {
        return UIStoryboard.mainStoryboard?.instantiateViewControllerWithIdentifier("LoginNC") as? LoginNavigationController
    }

}
```

Thanks~ I'm confused....

**Comment by carlosypunto** [comment]
Hi @DianQK, it is for not retain the returned UIViewController, take a look at the manual https://developer.apple.com/library/prerelease/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html#//apple_ref/doc/uid/TP40014097-CH20-ID48.

Maybe is better to use https://github.com/mac-cain13/R.swift for it

**Comment by dianqk** [comment]
Wa~~~R.swift is awesome repo~

So who remain the returned UIViewController?

**Comment by carlosypunto** [comment]
Oh, I'm sorry @DianQK I forget answer you I've been a little busy. 
`var loginNavigationController: LoginNavigationController?` in `ViewController` is retaining the returned Navigation controller.
And `var loginController: LoginViewController?` is retaining the first view controller of navigation controller

**Comment by carlosypunto** [comment]
I keep open the issue, for if other people arises the same question

**Comment by dianqk** [comment]
HiHi~ Thanks a lot ~ but if I modify code like this 

``` swift
private extension UIStoryboard {

    static var mainStoryboard: UIStoryboard? {
        return UIStoryboard(name: "Main", bundle: NSBundle.mainBundle())
    }

    static var loginNC: LoginNavigationController? {
        return UIStoryboard.mainStoryboard?.instantiateViewControllerWithIdentifier("LoginNC") as? LoginNavigationController
    }

```

All is right.

`LoginNavigationController` and `LoginViewController` will `deinit`.

**Comment by carlosypunto** [comment]
Thanks @DianQK for thinking, so people can decide

**Comment by werediver** [comment]
@carlosypunto I don't think you can force the caller to not retain the value returned from a function, and computed property is in fact just a function. To me `weak` in `weak static var x: X { return ... }` does not make any sense.

You're referring to the ARC chapter in the Swift documentation, but what exactly we should read? There is nothing about weak static computed properties.
